### ISSUE TITLE
Help ~~~~ bcrypt error?

### ISSUE THREAD

**Issue by smurfyuen** [learning-ionic/Chapter-6#1]
E:\Project\Learning Ionic_Code\Chapter 6\chapter6\chapter6\server>node server.js

[Error: %1 is not a valid Win32 application.
E:\Project\Learning Ionic_Code\Chapter 6\chapter6\chapter6\server\node_modules\m
ongojs\node_modules\mongodb\node_modules\bson\build\Release\bson.node]
js-bson: Failed to load c++ bson extension, using pure JS version
E:\Project\Learning Ionic_Code\Chapter 6\chapter6\chapter6\server\node_modules\b
crypt\node_modules\bindings\bindings.js:83
        throw e
              ^
Error: %1 is not a valid Win32 application.
E:\Project\Learning Ionic_Code\Chapter 6\chapter6\chapter6\server\node_modules\b
crypt\build\Release\bcrypt_lib.node
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at bindings (E:\Project\Learning Ionic_Code\Chapter 6\chapter6\chapter6\serv
er\node_modules\bcrypt\node_modules\bindings\bindings.js:76:44)
    at Object.<anonymous> (E:\Project\Learning Ionic_Code\Chapter 6\chapter6\cha
pter6\server\node_modules\bcrypt\bcrypt.js:3:35)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)

**Comment by arvindr21** [comment]
Looks like an issue with bcrypt module on windows. Try uninstalling the module and installing it again.
